 const coorperationData=[
    {
        order:1,
        name:'三 亚 屋 奇 酒 店',
        belong:'hotel',
        desc:'旅游度假公寓式酒店',
        rentNumber:'330万+',
        roomNumber:'72间',
        productStyle:'现代简约',
        itemBackground:'总部位于北京，正在三亚、成都分别建立超过5个分部管理；引进公寓全智能管理系统，开创无人化入住体验，建立全国超过30个城市的公寓预定平台；打造优质公寓产品，使闲置资源创造新的价值，将优质资源打造成的海边度假公寓。',
        itemAbout:'酒店规模9层，大堂空间100平米；客房72套，直梯配套，客房平均面积从25~45平米，带9套LOFT空间客房。',
        type:'酒店',
        keyWord:'生活主题、公寓式酒店、有温度、家',
        area:'海南三亚',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:2,
        name:'华轩里酒店广州珠江新城店',
        belong:'hotel',
        desc:'旅游度假公寓式酒店',
        rentNumber:'800万+',
        roomNumber:'309间',
        productStyle:'新中式',
        itemBackground:'项目位于广州繁华区域（珠江新城），物业租赁期20年，房间数量309间，酒店按照四星级标准装修。',
        itemAbout:'酒店总投资约4900万元人民币，家具采购总额980万元。',
        type:'酒店',
        keyWord:'新中式、禅意、轻奢、智能、环保',
        area:'广东广州',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:3,
        name:'华轩里酒店佛山顺德店',
        belong:'hotel',
        desc:'商务型酒店',
        rentNumber:'500万+',
        roomNumber:'156间',
        productStyle:'新中式',
        itemBackground:'项目位于佛山顺德，距佛山轨道3号线北滘新城站500米，广州地铁7号线林头站800米，面对的消费人群为商旅人群，公司白领以上人群。',
        itemAbout:'酒店总投资约2500万元人民币；有健身房，会议室，餐吧，书吧配套设施；一楼大堂1000平米左右  23-28层客房面积8600平米左右。',
        type:'酒店',
        keyWord:'新中式、禅意、轻奢、智能、环保',
        area:'广东佛山',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:4,
        name:'锐思堡国际公寓',
        belong:'apartment',
        desc:'商务型酒店式公寓',
        rentNumber:'1080万+',
        roomNumber:'360间',
        productStyle:'欧美',
        itemBackground:'地铁1、2号线交汇处、地铁直通火车站、火车南站、轻轨驳接机场。周边优势为长沙五一广场核心商圈、王府井、平和堂、步行街、大平街、火宫殿等。',
        itemAbout:'酒店总投资约1800万元人民币，客房单价在260-360左右。',
        type:'公寓',
        keyWord:'舒适、轻奢、有温度、家',
        area:'湖南长沙',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:5,
        name:'熙之行时代公寓-万科V寓',
        belong:'apartment',
        desc:'商务型酒店式公寓',
        rentNumber:'900万+',
        roomNumber:'300间',
        productStyle:'现代简约',
        itemBackground:'深圳市熙之行时代公寓有限公司隶属熙之行国际酒店管理有限公司，集团未来3年将在北上广深等GDP前十的城市中心区域或中国旅游消费力前十城市快速扩张，未来五年实现门店总数超3000家，并积极扩张至东南亚、欧洲等海外市场，努力跻身为全球前五的中国酒店集团。',
        itemAbout:'酒店总投资约1500万元人民币，有健身房、泳池、会议、餐吧、书吧配套设施，面对高端商务客、商端长租居家。',
        type:'公寓',
        keyWord:'高端、商务、温度、居家、智能、环保',
        area:'广东深圳',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:6,
        name:'华 里 - 里 寓 公 寓',
        belong:'apartment',
        desc:'商务型酒店式公寓',
        rentNumber:'110万+',
        roomNumber:'114间',
        productStyle:'新中式',
        itemBackground:'项目位于深圳西丽大学城区域，具体为坪山一路，哈工大研究生院南门正对面，有多路公交车经过，具备便捷的通达性，地铁5号线（大学城站）距离项目仅几分钟路程。',
        itemAbout:'配套咖啡吧、书吧、餐厅，客房单价在350元/天/间。',
        type:'公寓',
        keyWord:'新中式、禅意',
        area:'广东深圳',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:7,
        name:'上 海 雀 域',
        belong:'apartment',
        desc:'长短租公寓',
        rentNumber:'190万+',
        roomNumber:'106间',
        productStyle:'后现代',
        itemBackground:'项目位于上海市长寿路，打造集合联合办公、长租公寓、短租公寓相结合的产业链生态体系，物业租赁期18年，面对人群为高级白领以及商务出行人士。整体极具设计感，风格以后现代轻奢为主。周边优势为产业园区，具有极丰富的人流量及入住率。',
        itemAbout:'项目总投资约2500万人民币，配置健身房、会议、联合办公、等配套设施。',
        type:'公寓',
        keyWord:'现代、轻奢、设计感、后现代',
        area:'上海',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:8,
        name:'上 海 寓 居',
        belong:'apartment',
        desc:'长短租公寓',
        rentNumber:'150万+',
        roomNumber:'130间',
        productStyle:'现代简约',
        itemBackground:'项目距离上海彭浦新村地铁站300米，风格：宜家风，房型：6种，有部分loft公寓。针对蓝领、白领两种不同人群，注重房屋的整体性，以定制类产品为主，适应房间结构，增强居住感。',
        itemAbout:'项目总投资约900万元，周边为产业园。',
        type:'公寓',
        keyWord:'现代简约',
        area:'上海',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:9,
        name:'长沙步步高公寓',
        belong:'apartment',
        desc:'商务型酒店式公寓',
        rentNumber:'80万+',
        roomNumber:'56间',
        productStyle:'现代轻奢',
        itemBackground:'项目位于长沙步步高梅溪新天地，梅溪湖国际新城核心腹地，集大型美式Shoppingmall、国际时尚居广场、情景式时尚街区、写字楼、住宅等商业形态于一体的国际城市综合体。更有28米超高巨幕的电影院，室内高尔夫练习场、全国数一数二的飞行体验馆等新型业态，配套8000个停车位。',
        itemAbout:'项目总投资约324万。',
        type:'公寓',
        keyWord:'现代简约、商务、高级灰',
        area:'湖南长沙',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:10,
        name:'广 州 YOU+ 公 寓',
        belong:'apartment',
        desc:'长租公寓',
        rentNumber:'300万+',
        roomNumber:'400间',
        productStyle:'工业风',
        itemBackground:'YOU+国际青年社区是由一群从海外归来，追求梦想的青年人共同创建。整个青年借鉴了欧洲大学公寓的模式；融入了loft设计风格；搭建了国际青年旅社的交流平台；改变了都市时尚青年的生活态度。',
        itemAbout:'loft房、飘窗房、衣帽间房、阳台房、一房一厅等满足不同需求。会议厅、办公厅、茶歇区、观影区、健身房、瑜伽房、娱乐区、中央厨房、洗衣房等公区设施。房屋租金2000~4500不等。',
        type:'公寓',
        keyWord:'简约、现代、工业风',
        area:'广东广州',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:11,
        name:'深圳1980新派公寓',
        belong:'apartment',
        desc:'长租公寓',
        rentNumber:'待定',
        roomNumber:'151间',
        productStyle:'自然简约',
        itemBackground:'项目位于深圳1980文化创意园区内。该创意园属于政府扶持项目，3期共计划引进1100家企业，潜在客户群庞大，园区配套设施较为完善，可共享此类资源。毗邻百强企业富士康、华为的工业区；周边1KM以内有6栋较大的写字楼，步行或骑行仅需10分钟；毗邻主干道，处于龙华新区的中心地带，距大浪、清湖、民治、深圳北站等区域均不超过15分钟车程。',
        itemAbout:'项目租赁周期10年，面对客户：创客、周边中小企业管理层。增值服务：可共享园区的相关配套（如停车场、便利店、咖啡厅、屋顶花园等）；另外，项目落成后，新派将寻求外部合作，如洗衣、巴士服务等，为顾客提供增值服务。华南地区，深圳第一个项目，预计开业时间2018年7月11日。',
        type:'公寓',
        keyWord:'融合、包容、注重人文交流、自然',
        area:'广东深圳',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:12,
        name:'韶关市粤华电力有限公司',
        belong:'company',
        desc:'办公室自用',
        rentNumber:'340万+',
        roomNumber:'24000平',
        productStyle:'实用稳重',
        itemBackground:'国粤投资集团有限公司（简称：国粤集团）是一家跨地区、集团化经营的民营企业，成立于2010年，集团总部设在深圳市福田中心区，注册资本2亿元；集团原名为深圳市粤华投资控股有限公司，其前身为成立于1998年的深圳市粤华投资集团有限公司。集团主要从事能源建设与投资（包括水电、火电、太阳能、风能及综合利用等）、房地产投资开发、旅游地产开发、高科技研发、矿业和金融投资等。韶关粤华电力有限公司属于深圳市国粤集团旗下全资子公司，该项目位于韶关市浈江区，总投资24亿元。2017年5月正式投产。',
        itemAbout:'该项目首期为办公室自用办公家具，总共8层楼，每层约3000平方，总面积超24000平方。合同额212万人民币。项目二期为自用高档公寓，总共6层，每层10套公寓+一套领导公寓，总共66套公寓，活动家私合同额137万人民币。三期补充工程正在进行中，两层楼，每层3000平方，共6000平方。',
        type:'办公场所',
        keyWord:'传统、实用、稳重',
        area:'广东韶关',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:13,
        name:'深圳市绿景房地产开发有限公司',
        belong:'company',
        desc:'办公室自用',
        rentNumber:'420万+',
        roomNumber:'20000平',
        productStyle:'时尚高档',
        itemBackground:'绿景成立于1984年，是一家多元化国际企业集团，拥有房地产开发与经营、金融投资平台以及高新科学技术三大核心产业板块。三十余年激情进取，三大核心产业板块优势互补、协同发展，绿景已构筑完整的绿色人居产业全链条生态系统，为城市发展保驾护航。绿景地产板块成功运营二十余年，长期专注于中国经济高速增长的珠三角、长三角等核心区域，开发建设并运营深圳、珠海、化州、苏州、东莞等地项目，连续多年蝉联深圳市房地产综合实力前十强榜单，成为华南品牌企业前十强。2015年，绿景（中国）在香港成功上市（港交所代号：00095HK）。旗下绿景资产管理公司成功运营了以“佐阾”和“NEO”为代表的商业地产系列；旗下绿景物业管理公司具有国家物业管理企业一级资质，为各类物业提供全面优质的物业管理服务；旗下首个高星级酒店，绿景锦江酒店坐落于深圳中心商业区，完善的设施为顾客提供全方位的顶级服务。',
        itemAbout:'该项目位于深圳市福田区NEO大厦，绿景总部大楼。55--62层，每层2500平方，总共8层。每层约2500平方楼面面积。全部办公家具从签订合同到交付使用，持续一年时间。',
        type:'办公场所',
        keyWord:'时尚、实用、高档',
        area:'广东深圳',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    },
    {
        order:14,
        name:'基伍国际有限公司',
        belong:'company',
        desc:'办公室自用',
        rentNumber:'220万+',
        roomNumber:'3500平',
        productStyle:'时尚高档',
        itemBackground:'G\'FIVE集团座落在深圳市龙岗区坂田上雪科技工业城，是一家致力于通讯产品的研发与销售的高科技集团企业，下属的公司有：基伍国际有限公司，基伍伟业通讯设备（深圳）有限公司， 杰而望（香港）国际有限公司，杰而望（北京）科贸有限公司，深圳市杰而望精密模具制品有限公司，深圳市京维天科技有限公司，深圳市京维天保健器材有限公司和深圳市爱波通讯有限公司等。',
        itemAbout:'基伍国际有限公司总部位于深圳市龙岗区坂田，香港分公司位于香港特别行政区荃湾区海盛路9号有线电视大楼19F。整体办公家具高档豪华。客户反映很好，目前零返修。',
        type:'办公场所',
        keyWord:'时尚、实用、高档',
        area:'香港荃湾区',
        url:require('../../../img/u319.png'),
        children:[
            {
                url:require('../../../img/p8.jpg'),
            },
            {
                url:require('../../../img/p10.jpg'),
            },
            {
                url:require('../../../img/p13.jpg'),
            }
        ]
    }
]

export default function filterCoorperation(key,value){
    if(key&&value){
      return  coorperationData.filter((item=>{
            return item[key]==value;
        }))
    }else{
        return coorperationData
    }
}

